### PR TITLE
Upgraded cmake configuration

### PR DESCRIPTION
**Pull request by Pfeifenjoy**
Hello,

I have changed the cmake configuration such that it uses targets and is easier to install.

You can now run `cmake .. && make && make install` to install this library.
If you want to use it in another cmake project you can add

```
find_package(lexertl REQUIRED)

add_executable(myexe main.cpp)
target_link_libraries(myexe PRIVATE lexertl::lexertl)
```

to your project.
This will automatically include all the header files into the project (target).

Furthermore I have fixed some minor warnings and upgraded the
required c++ standard of the unicode example to c++11 since I
got a compile time error using clang.

### CODE REVIEW

**Comment by BenHanson** [comment]
Note that lexertl is a C++98/03 code base. lexertl14 is written for C++14 (it uses unique_ptr instead of auto_ptr for example).

**Comment by Pfeifenjoy** [comment]
@BenHanson The c++11 upgrade is related to the unicode example since it was using c++11 and I got a compile error when I tried to compile it with c++03.

**Comment by BenHanson** [comment]
@Pfeifenjoy OK, that makes sense. I will have a proper look later today.

**Comment by BenHanson** [comment]
Times have moved on and I have realised that all these extra files should be under lexertl14. I will therefore move everything over and make it obvious that lexertl14 is the main version now.

Thanks for your work.

**Pull request merged**
