### PR TITLE
Respect icase flag with characters specified by hexademical codes.

### PR DESCRIPTION
**Pull request by akmerkator**
Currently icase flag is not respected when characters are specified by hexademical codes.
Some case folding mappings are missing.
This PR fixes that which allows the rule with regular expression "\\x438" and icase flag set to lex both letters "и" and "И".

### CODE REVIEW

**Comment by BenHanson** [comment]
There were two places that icase needed fixing. Thanks for reporting that. I will look at the folding issue separately as there are ranges missing in addition to the ones you reported their too.

**Comment by akmerkator** [comment]
Thank you! Closing PR.

**Comment by BenHanson** [comment]
The fold tables have been updated, however I've also noticed that my UnicodeData.txt file is from 2010 (v6). There is now a v8 that was released this year, so I will update all the Unicode tables with the new version.

**Comment by BenHanson** [comment]
I have now updated the tables to use Unicode v8.

**Pull request closed without merging**
